-- AlterTable
ALTER TABLE `document` ADD COLUMN `cgstAmount` DECIMAL(12, 2) NOT NULL DEFAULT 0,
    ADD COLUMN `cgstPercent` DECIMAL(5, 2) NOT NULL DEFAULT 0,
    ADD COLUMN `gstType` ENUM('CGST_SGST', 'IGST') NOT NULL DEFAULT 'CGST_SGST',
    ADD COLUMN `igstAmount` DECIMAL(12, 2) NOT NULL DEFAULT 0,
    ADD COLUMN `igstPercent` DECIMAL(5, 2) NOT NULL DEFAULT 0,
    ADD COLUMN `sgstAmount` DECIMAL(12, 2) NOT NULL DEFAULT 0,
    ADD COLUMN `sgstPercent` DECIMAL(5, 2) NOT NULL DEFAULT 0;
